# Generated by Django 5.1.7 on 2025-04-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'park_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('total_seats', models.PositiveIntegerField(default=24)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('on_trip', 'Currently on Trip')], default='available', max_length=20)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.buspark')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['state', 'name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.AddField(
            model_name='buspark',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='core.city'),
        ),
        migrations.CreateModel(
            name='IndirectRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField()),
                ('total_price', models.FloatField()),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_ends', to='core.city')),
                ('start_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_starts', to='core.buspark')),
                ('transit_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_points', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('estimated_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('destination_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_routes', to='core.buspark')),
                ('origin_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.buspark')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('seat_price', models.FloatField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.route')),
            ],
            options={
                'ordering': ['departure_datetime'],
                'unique_together': {('route', 'bus', 'departure_datetime')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.trip')),
            ],
        ),
    ]
