# Generated by Django 5.1.7 on 2025-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
