# Generated by Django 5.1.7 on 2025-07-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='core.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='core.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'seat_number'], name='core_seatas_trip_id_6547c0_idx')],
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
