# Generated by Django 5.1.7 on 2025-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
